Fix: `react-query` mutation error
The `react-query` `useMutation` hook is throwing a `TypeError` because `defaultMutationOptions` is not a function.  This commit aims to resolve this error.